apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z mysql 3306; do
              echo "Waiting for MySQL..."
              sleep 5
            done
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}

            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}

            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}

            - name: DB_USER
              value: {{ .Values.env.DB_USER | quote }}

            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD | quote }}
